[package]
name = "math"
author = "xnguye27"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4"
rand = "0.8.5"
thiserror = "1"
once_cell = "1"
libm = "0.2"
